apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl-sa
  namespace: curling
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: webbis
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: webbis
subjects:
- kind: ServiceAccount
  name: curl-sa
  namespace: curling
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io