apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mesbonslegumesbio-ingress
spec:
  rules:
  - host: "mesbonslegumes.fr"
    http:
      paths:
      - path: /bio
        pathType: Prefix
        backend:
          service:
            name: mesbonslegumesbio-service
            port:
              number: 80