apiVersion: v1
kind: Namespace
metadata:
  name: backup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
  namespace: backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-sa-binding
subjects:
- kind: ServiceAccount
  name: backup-sa
  namespace: backup
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: backup
spec:
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    - mountPath: /mnt/data
      name: backup-storage
  volumes:
  - name: backup-storage
    persistentVolumeClaim:
      claimName: backup-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: backup-etcd
  namespace: backup
spec:
  template:
    spec:
      serviceAccountName: backup-sa
      containers:
      - name: etcd-backup-container
        image: rancher/etcd:v3.4.13
        command:
          - /bin/sh
          - -c
          - |
            etcdctl snapshot save /backup/etcd-snapshot.db
      restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-backup-etcd
  namespace: backup
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-sa
          containers:
          - name: etcd-backup-container
            image: rancher/etcd:v3.4.13
            command:
              - /bin/sh
              - -c
              - |
                etcdctl snapshot save /backup/etcd-snapshot-$(date +\%Y-\%m-\%d).db
          restartPolicy: Never
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data

