apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesbonslegumes-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mesbonslegumes
  template:
    metadata:
      labels:
        app: mesbonslegumes
    spec:
      containers:
      - name: mesbonslegumes
        image: sayk/mesbonslegumes:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"