apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesbonslegumesbio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mesbonslegumesbio
  template:
    metadata:
      labels:
        app: mesbonslegumesbio
    spec:
      containers:
      - name: mesbonslegumesbio
        image: tonusername/mesbonslegumesbio:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mesbonslegumesbio-service
spec:
  selector:
    app: mesbonslegumesbio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mesbonslegumesbio-ingress
spec:
  rules:
  - host: "mesbonslegumes.fr"
    http:
      paths:
      - path: /bio
        pathType: Prefix
        backend:
          service:
            name: mesbonslegumesbio-service
            port:
              number: 80