apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesbonslegumesbio-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mesbonslegumesbio
  template:
    metadata:
      labels:
        app: mesbonslegumesbio
    spec:
      containers:
      - name: mesbonslegumesbio
        image: sayk/mesbonslegumesbio:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"